; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Sep 25 2020 17:07:52 GMT-0700 (Pacific Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


