; homeu.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Sep 25 2020 17:07:53 GMT-0700 (Pacific Daylight Time)
M400 G91          ; relative positioning
G1 H2 U-0.2 F200  ; lift U relative to current position
G1 H1 U30         ; move Z down until the endstop is triggered
G1 U-2            ; go up a few mm
G1 H1 U3 F50      ; 
G1 U-1.0 F200     ; ease off the endstop
G90               ; absolute positioning
M400
