; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Sep 25 2020 17:07:53 GMT-0700 (Pacific Daylight Time)
M400 G91          ; relative positioning
G1 H2 Z-2 F1000   ; lift Z relative to current position
G1 H1 Z3000        ; move Z down until the endstop is triggered
G1 Z-3            ; go up a few mm
G1 H1 Z10 F200    ; 
G1 Z-2 F1000      ; ease off the endstop
G90               ; absolute positioning
M400

